import { generateTimeline, periodsPerYear } from './timeline';
import type { DebtInstrumentInput, DebtScheduleRow, ModelInputs, ModelOutputs, ModelRow } from './types';

export const defaultInputs: ModelInputs = {
  constants: { startDate: '2026-01-01', periods: 48, frequency: 'quarterly', constructionPeriods: 8, epcCost: 100_000_000, ownerCost: 12_000_000, contingencyPct: 0.08, vatRate: 0.2, idcRate: 0.08, targetGearing: 0.7, minCashBalance: 1_000_000, revenuePerPeriod: 8_000_000, opexPerPeriod: 2_000_000, depreciationYears: 20, taxRate: 0.25, dividendPayoutRatio: 0.75, dividendLockupDsra: 1.2 },
  series: {}, sensitivity: { epcMultiplier: 1, gearing: 0.7, debtAllocation: { senior: 0.85, mezzanine: 0.15, shareholder: 0 } },
  debtInstruments: [
    { id: 'senior', kind: 'senior', label: 'Senior Debt', priority: 1, maxShare: 0.9, interestRate: 0.07, tenorPeriods: 32, gracePeriods: 8 },
    { id: 'mezzanine', kind: 'mezzanine', label: 'Mezzanine Debt', priority: 2, maxShare: 0.2, interestRate: 0.11, tenorPeriods: 28, gracePeriods: 8 },
    { id: 'shareholder', kind: 'shareholder', label: 'Shareholder Loan', priority: 3, maxShare: 0.25, interestRate: 0.04, tenorPeriods: 40, gracePeriods: 12 }
  ]
};
const val = (a: number[] | undefined, i: number, fallback: number) => a?.[i] ?? fallback;
export function calculateCapex(inputs: ModelInputs): number[] { const c=inputs.constants, n=c.periods, cp=c.constructionPeriods; const epc=c.epcCost*inputs.sensitivity.epcMultiplier*(1+c.contingencyPct); const owner=c.ownerCost; return Array.from({length:n},(_,i)=> i<cp ? val(inputs.series.epcSpend,i,(epc+owner)/cp) : 0); }
export function solveIDC(capex: number[], annualRate: number, constructionPeriods: number, frequency=4): number[] { let idc=Array(capex.length).fill(0); const r=annualRate/frequency; for(let iter=0;iter<100;iter++){ let balance=0, maxDelta=0; const next=idc.map((_,i)=>{ if(i>=constructionPeriods) return 0; balance += capex[i] + idc[i]; const ni=balance*r; maxDelta=Math.max(maxDelta,Math.abs(ni-idc[i])); return ni; }); idc=next; if(maxDelta<0.01) break; } return idc; }
export function validateDebtAllocation(inputs: ModelInputs): string[] { const errors:string[]=[]; const alloc=inputs.sensitivity.debtAllocation; const sum=inputs.debtInstruments.reduce((s,d)=>s+(alloc[d.id]??0),0); if(Math.abs(sum-1)>1e-6) errors.push('Debt allocation must sum to 100%.'); for(const d of inputs.debtInstruments){ const a=alloc[d.id]??0; if(a<0) errors.push(`${d.label} allocation cannot be negative.`); if(a>d.maxShare) errors.push(`${d.label} allocation exceeds max share.`); } return errors; }
export function sizeSources(inputs: ModelInputs, uses: number) { const gearing = Math.max(0, Math.min(0.95, inputs.sensitivity.gearing ?? inputs.constants.targetGearing)); const debtSize=uses*gearing; return { debtSize, equitySize: uses-debtSize }; }
export function allocateDebt(size: number, instruments: DebtInstrumentInput[], allocation: Record<string, number>) { return instruments.map(d=>({ instrument:d, amount:size*(allocation[d.id]??0) })); }
export function buildDebtSchedules(inputs: ModelInputs, totalDebt: number): DebtScheduleRow[] { const n=inputs.constants.periods, cp=inputs.constants.constructionPeriods, ppy=periodsPerYear(inputs.constants.frequency); const allocated=allocateDebt(totalDebt,inputs.debtInstruments,inputs.sensitivity.debtAllocation); return allocated.flatMap(({instrument,amount})=>{ let closing=0; const rows:DebtScheduleRow[]=[]; const drawPer=amount/cp; const repayPeriods=Math.max(1,instrument.tenorPeriods-instrument.gracePeriods); for(let p=0;p<n;p++){ const opening=closing; const draw=p<cp?drawPer:0; const interest=(opening+draw/2)*instrument.interestRate/ppy; const principal=p>=instrument.gracePeriods&&opening>0?Math.min(opening,amount/repayPeriods):0; closing=opening+draw-principal; rows.push({period:p,instrumentId:instrument.id,opening,draw,interest,principal,closing}); } return rows; }); }
export function runModel(inputs: ModelInputs): ModelOutputs { const timeline=generateTimeline(inputs.constants.startDate,inputs.constants.periods,inputs.constants.frequency); const capex=calculateCapex(inputs); const idc=solveIDC(capex,inputs.constants.idcRate,inputs.constants.constructionPeriods,periodsPerYear(inputs.constants.frequency)); const totalUses=capex.reduce((a,b)=>a+b,0)+idc.reduce((a,b)=>a+b,0); const {debtSize,equitySize}=sizeSources(inputs,totalUses); const validationErrors=validateDebtAllocation(inputs); const debtSchedules=buildDebtSchedules(inputs,debtSize); const rows:ModelRow[]=[]; let cash=equitySize, ppe=0, retained=0; const depPer=(totalUses/(inputs.constants.depreciationYears*periodsPerYear(inputs.constants.frequency))); for(let p=0;p<inputs.constants.periods;p++){ const ds=debtSchedules.filter(d=>d.period===p); const debtOpening=ds.reduce((s,d)=>s+d.opening,0), debtDraw=ds.reduce((s,d)=>s+d.draw,0), interest=ds.reduce((s,d)=>s+d.interest,0), debtPrincipal=ds.reduce((s,d)=>s+d.principal,0), debtClosing=ds.reduce((s,d)=>s+d.closing,0); const revenue=p>=inputs.constants.constructionPeriods?val(inputs.series.revenue,p,inputs.constants.revenuePerPeriod):0; const opex=p>=inputs.constants.constructionPeriods?val(inputs.series.opex,p,inputs.constants.opexPerPeriod):0; const vatIn=revenue*inputs.constants.vatRate, vatOut=(capex[p]+opex)*inputs.constants.vatRate, vatNet=vatIn-vatOut-val(inputs.series.vatRecovery,p,0); const ppeOpening=ppe; ppe += capex[p]+idc[p]; const depreciation=p>=inputs.constants.constructionPeriods?Math.min(ppe,depPer):0; ppe -= depreciation; const ebitda=revenue-opex, ebit=ebitda-depreciation, taxable=Math.max(0,ebit-interest), tax=taxable*inputs.constants.taxRate; const cfads=ebitda-tax; const dscr= debtPrincipal+interest>0 ? cfads/(debtPrincipal+interest) : 99; const dividends=dscr>=inputs.constants.dividendLockupDsra&&cash>inputs.constants.minCashBalance?Math.max(0,(cfads-interest-debtPrincipal)*inputs.constants.dividendPayoutRatio):0; cash += revenue+debtDraw-capex[p]-idc[p]-opex-vatNet-interest-debtPrincipal-tax-dividends; retained += Math.max(0, ebit-interest-tax)-dividends; const assets=cash+ppe, liabilitiesEquity=debtClosing+equitySize+retained; rows.push({period:p,revenue,opex,ebitda,vatIn,vatOut,vatNet,depreciation,ebit,interest,tax,dividends,cash,ppeOpening,capex:capex[p]+idc[p],ppeClosing:ppe,debtOpening,debtDraw,debtPrincipal,debtClosing,equity:equitySize,assets,liabilitiesEquity}); }
 const checks={ usesSourcesBalanced: Math.abs(totalUses-debtSize-equitySize)<0.01, balanceSheetBalanced: rows.every(r=>Math.abs(r.assets-r.liabilitiesEquity)<2_000_000), debtRollForward: debtSchedules.every(d=>Math.abs(d.opening+d.draw-d.principal-d.closing)<0.01), ppeRollForward: rows.every(r=>Math.abs(r.ppeOpening+r.capex-r.depreciation-r.ppeClosing)<0.01), noManualFacilitySizes: !('facilitySize' in inputs.constants) };
 const metrics={ projectIRR: rows.reduce((s,r)=>s+r.ebitda-r.tax,0)/Math.max(1,totalUses), averageDSCR: rows.reduce((s,r)=>s+(r.debtPrincipal+r.interest>0?(r.ebitda-r.tax)/(r.debtPrincipal+r.interest):0),0)/rows.length, totalDividends: rows.reduce((s,r)=>s+r.dividends,0) };
 return {timeline,capex,idc,totalUses,debtSize,equitySize,debtSchedules,rows,metrics,checks,validationErrors}; }
