import { describe, expect, it } from 'vitest';
import { defaultInputs, runModel, solveIDC, validateDebtAllocation } from './financeEngine';
import { generateTimeline } from './timeline';
import type { ModelInputs } from './types';
const clone=():ModelInputs=>JSON.parse(JSON.stringify(defaultInputs));
describe('timeline',()=>{ it.each(['monthly','quarterly','semiAnnual','annual'] as const)('generates %s timeline',frequency=>{ const t=generateTimeline('2026-01-01',4,frequency,1); expect(t).toHaveLength(4); expect(t[0].label).toBe('2026-01'); expect(t[0].monthsInPeriod).toBeGreaterThan(0); }); });
describe('finance engine',()=>{
 it('IDC solver convergence',()=>{ const idc=solveIDC([100,100,0,0],0.12,2,4,.7); expect(idc[0]).toBeGreaterThan(1); expect(idc[1]).toBeGreaterThan(idc[0]); expect(idc[2]).toBe(0); });
 it('Uses/Sources balance',()=>{ const out=runModel(clone()); expect(out.checks.usesSourcesBalanced).toBe(true); expect(out.totalUses).toBeCloseTo(out.debtSize+out.equitySize,2); });
 it('Balance Sheet balances',()=>{ const out=runModel(clone()); expect(out.checks.balanceSheetBalanced).toBe(true); expect(out.rows.every(r=>Math.abs(r.assets-r.liabilitiesEquity)<.01)).toBe(true); });
 it('debt roll-forward',()=>{ const out=runModel(clone()); expect(out.checks.debtRollForward).toBe(true); });
 it('PP&E roll-forward',()=>{ const out=runModel(clone()); expect(out.checks.ppeRollForward).toBe(true); });
 it('dividend lock-up',()=>{ const i=clone(); i.constants.dividendLockupDsra=1000; const out=runModel(i); expect(out.rows.reduce((s,r)=>s+r.dividends,0)).toBe(0); });
 it('EPC sensitivity',()=>{ const base=runModel(clone()); const i=clone(); i.sensitivity.epcMultiplier=1.1; const inc=runModel(i); expect(inc.totalUses).toBeGreaterThan(base.totalUses); expect(inc.debtSize).toBeGreaterThan(base.debtSize); expect(inc.equitySize).toBeGreaterThan(base.equitySize); expect(inc.metrics.totalIDC).toBeGreaterThan(base.metrics.totalIDC); });
 it('gearing sensitivity',()=>{ const low=clone(); low.sensitivity.gearing=.5; const high=clone(); high.sensitivity.gearing=.8; expect(runModel(high).debtSize).toBeGreaterThan(runModel(low).debtSize); expect(runModel(high).equitySize).toBeLessThan(runModel(low).equitySize); });
 it('debt allocation sensitivity',()=>{ const a=clone(); const b=clone(); b.sensitivity.debtAllocation={senior:.75,mezzanine:.2,shareholder:.05}; const seniorA=runModel(a).debtSchedules.filter(d=>d.instrumentId==='senior').reduce((s,d)=>s+d.draw,0); const seniorB=runModel(b).debtSchedules.filter(d=>d.instrumentId==='senior').reduce((s,d)=>s+d.draw,0); expect(seniorB).toBeLessThan(seniorA); });
 it('debt allocation validation',()=>{ const i=clone(); i.sensitivity.debtAllocation={senior:1,mezzanine:.5,shareholder:0}; expect(validateDebtAllocation(i).length).toBeGreaterThan(0); });
});
describe('operations engine',()=>{
 it('calculates segment cabinet fill, cap, effective cabinets and power sold',()=>{const out=runModel(clone()); const row=out.operations.segmentRows.find(r=>r.segment==='retail'&&r.period===8)!; expect(row.cabinetsFilled).toBe(45); expect(row.cumulativeCabinets).toBeLessThanOrEqual(row.maxCabinets); expect(row.effectiveCabinets).toBeCloseTo(row.netCumulativeCabinets*.98); expect(row.powerSoldKw).toBeCloseTo(row.effectiveCabinets*defaultInputs.constants.segments.retail.powerSoldPerCabKw);});
 it('churn and renewal affect net cumulative cabinets after contract duration',()=>{const i=clone(); i.constants.frequency='annual'; i.constants.periods=8; i.constants.constructionPeriods=0; i.series.segments.retail.cabinetFill=[100,0,0,0,0,0,0,0]; i.series.segments.retail.churnPct=Array(8).fill(.5); i.series.segments.retail.renewalPct=Array(8).fill(0); const retail=runModel(i).operations.segmentRows.filter(r=>r.segment==='retail'); expect(retail[3].netCumulativeCabinets).toBeLessThan(retail[2].netCumulativeCabinets);});
 it('segment revenue equals power + space + interconnection',()=>{const r=runModel(clone()).operations.segmentRows.find(x=>x.segment==='csp'&&x.period===10)!; expect(r.totalRevenue).toBeCloseTo(r.powerRevenue+r.spaceRevenue+r.interconnectionRevenue,2);});
 it('total revenue switch selects input or calculated mode',()=>{const calc=runModel(clone()).operations.rows[8]; const i=clone(); i.constants.operations.revenueMode='input'; i.series.revenue=Array(48).fill(12345); const input=runModel(i).operations.rows[8]; expect(calc.revenue).toBe(calc.calculatedRevenue); expect(input.revenue).toBe(12345);});
 it('property management fee is based on revenue excluding electricity cost',()=>{const out=runModel(clone()); const r=out.operations.rows[10]; expect(r.propertyManagementFee).toBeCloseTo(defaultInputs.constants.operations.propertyManagementFeeRate*Math.max(0,r.revenue-r.electricityCost),2);});
 it('utility cost uses PUE, power drawn, days, hours and tariff',()=>{const out=runModel(clone()); const r=out.operations.rows[9]; const expected=defaultInputs.constants.operations.pue*24*out.timeline[9].daysInPeriod*r.totalPowerDrawnKw*defaultInputs.constants.operations.blendedTariff*(defaultInputs.series.electricityIndexation?.[9]??1); expect(r.electricityCost).toBeCloseTo(expected,2);});
 it('direct labour and facility management switches select input mode',()=>{const i=clone(); i.constants.operations.directLabourMode='input'; i.constants.operations.facilityManagementMode='input'; i.series.directLabourCost=Array(48).fill(777); i.series.facilityManagementFee=Array(48).fill(888); const r=runModel(i).operations.rows[8]; expect(r.directLabour).toBe(777); expect(r.facilityManagementFee).toBe(888);});
 it('S&M fee applies only to selected segments',()=>{const i=clone(); for(const s of ['retail','enterprise','csp','lqc','ai'] as const)i.constants.segments[s].salesMarketingApplies=false; expect(runModel(i).operations.rows[10].salesMarketingFee).toBe(0);});
 it('working capital AR/AP balances reconcile and feed model rows',()=>{const out=runModel(clone()); const r=out.operations.rows[12]; expect(r.accountsReceivable).toBeGreaterThan(0); expect(r.accountsPayable).toBeGreaterThan(0); expect(out.rows[12].accountsReceivable).toBe(r.accountsReceivable); expect(out.checks.workingCapitalReconciles).toBe(true);});
});
