import type { CustomerSegment, ModelInputs, OperationsOutput, OperationsRow, Period, SegmentOperationRow } from './types';
const segments: CustomerSegment[] = ['retail','enterprise','csp','lqc','ai'];
const v=(a:number[]|undefined,i:number,f=0)=>a?.[i]??f;
const pct=(x:number)=>x;
export function calculateOperations(inputs: ModelInputs, timeline: Period[], capex: number[]): OperationsOutput {
  const errors:string[]=[]; const checks:Record<string,boolean>={}; const c=inputs.constants, oc=c.operations; const segmentRows:SegmentOperationRow[]=[]; const rows:OperationsRow[]=[];
  const cumulative:Record<CustomerSegment,number>={retail:0,enterprise:0,csp:0,lqc:0,ai:0}; const net:Record<CustomerSegment,number>={retail:0,enterprise:0,csp:0,lqc:0,ai:0}; const history:Record<CustomerSegment,number[]>={retail:[],enterprise:[],csp:[],lqc:[],ai:[]}; let prevAR=0, prevAP=0;
  checks.contractPortionsSumTo100=true; checks.noNegativeCabinets=true; checks.cabinetsWithinCapacity=true; checks.effectiveWithinCumulative=true; checks.nonNegativeRevenue=true; checks.opexSignsCorrect=true; checks.electricityConsumptionConsistent=true; checks.propertyManagementBaseCorrect=true; checks.switchesApplied=true; checks.workingCapitalReconciles=true;
  for (const seg of segments){ const sc=c.segments[seg]; const sum=sc.contractPortion1Pct+sc.contractPortion2Pct; if(sc.active&&Math.abs(sum-1)>1e-6){errors.push(`${seg} contract portions must sum to 100%.`); checks.contractPortionsSumTo100=false;} if(sc.cabinetUtilizationPct<0||sc.cabinetUtilizationPct>1){errors.push(`${seg} utilization must be between 0% and 100%.`);} }
  timeline.forEach((p)=>{
    const revIdx=v(inputs.series.revenueIndexation,p.index,1), elecIdx=v(inputs.series.electricityIndexation,p.index,1), costIdx=v(inputs.series.costIndexation,p.index,1); const segRevenue={} as Record<CustomerSegment,number>; const effCab={} as Record<CustomerSegment,number>;
    let calcRevenue=0, install=0,totalSoldKw=0,totalDrawnKw=0,totalInterconnectRevenue=0;
    for (const seg of segments){ const sc=c.segments[seg], ss=inputs.series.segments[seg]; if(!sc.active){ segRevenue[seg]=0; effCab[seg]=0; continue; }
      const fill=v(ss.cabinetFill,p.index,0); if(fill<0){errors.push(`${seg} cabinet fill cannot be negative.`); checks.noNegativeCabinets=false;}
      const ramp=v(ss.rampUpPct,p.index,1); const sensitivityReduction=(inputs.sensitivity.rampUpReductionPct??0)+(sc.rampUpReductionPct??0); const maxCab=sc.cabinetsAvailable*Math.max(0,Math.min(1,sc.cabinetUtilizationPct+(inputs.sensitivity.utilizationChangePct??0)))*(1-Math.max(0,sensitivityReduction));
      const filled=Math.max(0,fill*ramp*p.operatingProration); cumulative[seg]=Math.min(maxCab,cumulative[seg]+filled); if(cumulative[seg]>maxCab+1e-6) checks.cabinetsWithinCapacity=false;
      const duration1Periods=Math.round(sc.contractDuration1Years*p.periodsPerYear), duration2Periods=Math.round(sc.contractDuration2Years*p.periodsPerYear); const matured1=history[seg][p.index-duration1Periods]??0; const matured2=history[seg][p.index-duration2Periods]??0;
      const churnRate=v(ss.churnPct,p.index,0); const renewalRate=v(ss.renewalPct,p.index,1); if(churnRate<0||churnRate>1||renewalRate<0||renewalRate>1){errors.push(`${seg} churn/renewal must be between 0% and 100%.`);} const matured=matured1*sc.contractPortion1Pct + matured2*sc.contractPortion2Pct; const churned=matured*churnRate; const renewed=matured*renewalRate; net[seg]=Math.max(0,Math.min(maxCab,net[seg]+filled-churned+renewed)); history[seg][p.index]=filled;
      const effectiveRate=v(ss.effectiveRatePct,p.index,1); const effective=Math.min(net[seg]*effectiveRate,net[seg]); if(effective>net[seg]+1e-6) checks.effectiveWithinCumulative=false; const powerSoldKw=effective*sc.powerSoldPerCabKw; const powerDrawnKw=powerSoldKw*sc.powerDrawnRate; const haircut=(sc.pricingHaircutPct??0)+(inputs.sensitivity.pricingHaircutPct[seg]??0); const powerChargedKw=sc.powerDrawnRate>0?powerDrawnKw/sc.powerDrawnRate:powerDrawnKw;
      const powerRevenue=powerChargedKw*sc.powerPricePerKw*p.monthsInPeriod*elecIdx*p.operatingProration*(1-haircut); const spaceRevenue=powerSoldKw*sc.spacePricePerKw*p.monthsInPeriod*revIdx*p.operatingProration*(1-haircut); const interconnectionRevenue=powerSoldKw*sc.interconnectionPricePerKw*p.monthsInPeriod*revIdx*p.operatingProration*(1-haircut); const totalRevenue=powerRevenue+spaceRevenue+interconnectionRevenue; const installationFeeRevenue=Math.max(0,effective-((()=>{const a=segmentRows.filter(r=>r.segment===seg);return a.length?a[a.length-1].effectiveCabinets:0})()))*sc.installationFeePerCabinet;
      segRevenue[seg]=totalRevenue; effCab[seg]=effective; calcRevenue+=totalRevenue+installationFeeRevenue; install+=installationFeeRevenue; totalSoldKw+=powerSoldKw; totalDrawnKw+=powerDrawnKw; totalInterconnectRevenue+=interconnectionRevenue;
      segmentRows.push({segment:seg,period:p.index,cabinetsFilled:filled,cumulativeCabinets:cumulative[seg],churnedCabinets:churned,renewedCabinets:renewed,netCumulativeCabinets:net[seg],effectiveCabinets:effective,powerSoldKw,powerSoldMw:powerSoldKw/1000,powerDrawnKw,powerRevenue,spaceRevenue,interconnectionRevenue,totalRevenue,installationFeeRevenue,maxCabinets:maxCab});
    }
    const inputRevenue=v(inputs.series.revenue,p.index,c.revenuePerPeriod)*p.operatingProration; const revenue=oc.revenueMode==='input'?inputRevenue:calcRevenue; if(revenue<0) checks.nonNegativeRevenue=false;
    const tariffBase=oc.tariffSelection==='grid'?oc.gridTariff:oc.tariffSelection==='ppa1'?oc.ppa1Tariff:oc.tariffSelection==='ppa2'?oc.ppa2Tariff:oc.blendedTariff; const tariff=tariffBase*(1+(inputs.sensitivity.electricityCostIncreasePct??0)); const consumption=(oc.pue+(inputs.sensitivity.pueChange??0))*oc.hoursPerDay*p.daysInPeriod*totalDrawnKw*p.operatingProration; const electricityCost=consumption*tariff*elecIdx; const interconnectionCost=totalInterconnectRevenue*oc.interconnectionCostRate; const utility=electricityCost+interconnectionCost;
    const directCalc=(oc.salaryPerPersonAnnual/12)*oc.headcount*p.monthsInPeriod*costIdx*(1+oc.directLabourMarkupRate)*p.operatingProration; const directLabour=oc.directLabourMode==='input'?v(inputs.series.directLabourCost,p.index,directCalc)*p.operatingProration:directCalc;
    const pmCalc=oc.propertyManagementFeeRate*Math.max(0,revenue-electricityCost); const propertyManagementFee=oc.propertyManagementMode==='input'?v(inputs.series.propertyManagementFee,p.index,pmCalc)*p.operatingProration:pmCalc;
    if(Math.abs(pmCalc-oc.propertyManagementFeeRate*Math.max(0,revenue-electricityCost))>0.01) checks.propertyManagementBaseCorrect=false;
    const fmCalc=oc.otherOpexMarkupRate*Math.max(0,revenue-utility)+oc.facilityDirectLabourMarkupRate*directLabour+oc.powerFeePctOfUtility*utility; const facilityManagementFee=oc.facilityManagementMode==='input'?v(inputs.series.facilityManagementFee,p.index,fmCalc)*p.operatingProration:fmCalc;
    const selectedSmRevenue=segments.reduce((s,seg)=>s+(c.segments[seg].salesMarketingApplies?segRevenue[seg]:0),0); const salesMarketingFee=selectedSmRevenue*oc.salesMarketingRate*oc.salesMarketingAdditionalProportion; const salesCommission=revenue*oc.salesCommissionRate; const assetManagementFee=revenue*oc.assetManagementFeeRate; const insurance=oc.insuranceAnnual/p.periodsPerYear*costIdx*p.operatingProration; const spvCosts=oc.spvAnnual/p.periodsPerYear*costIdx*p.operatingProration; const slaPenalties=oc.downtimeMinutesPerMonth*p.monthsInPeriod*oc.downtimeReferencePricePerMinute*oc.downtimeCrashProbability*p.operatingProration; const lifecycleCosts=oc.lifecycleEnabled && p.isOperating && oc.lifecycleEveryYears>0 && p.index>c.constructionPeriods && ((p.index-c.constructionPeriods)%Math.round(oc.lifecycleEveryYears*p.periodsPerYear)===0) ? capex.reduce((a,b)=>a+b,0)*oc.lifecycleCostPctOfCapex : 0;
    const totalOpex=(utility+salesCommission+assetManagementFee+directLabour+propertyManagementFee+facilityManagementFee+salesMarketingFee+insurance+spvCosts+slaPenalties+lifecycleCosts)*(1+(inputs.sensitivity.opexIncreasePct??0)); if(totalOpex<0) checks.opexSignsCorrect=false; const ebitda=revenue-totalOpex; const ar=revenue*oc.debtorDays/p.daysInPeriod; const ap=totalOpex*oc.creditorDays/p.daysInPeriod; const changeWC=(ar-prevAR)-(ap-prevAP); prevAR=ar; prevAP=ap; const cfads=ebitda-changeWC;
    rows.push({period:p.index,revenueInput:inputRevenue,calculatedRevenue:calcRevenue,revenue,installationFeeRevenue:install,totalPowerSoldKw:totalSoldKw,totalPowerSoldMw:totalSoldKw/1000,totalPowerDrawnKw:totalDrawnKw,electricityConsumptionKwh:consumption,electricityCost,interconnectionCost,totalUtilityExpense:utility,salesCommission,assetManagementFee,directLabour,propertyManagementFee,facilityManagementFee,salesMarketingFee,insurance,spvCosts,slaPenalties,lifecycleCosts,totalOpex,ebitda,accountsReceivable:ar,accountsPayable:ap,changeInWorkingCapital:changeWC,cfadsBeforeDebtService:cfads,segmentRevenue:segRevenue,effectiveCabinets:effCab});
  });
  return {rows,segmentRows,validationErrors:errors,validationChecks:checks};
}
