export type Frequency = 'monthly' | 'quarterly' | 'semiAnnual' | 'annual';
export type DebtKind = 'senior' | 'mezzanine' | 'shareholder';
export type CustomerSegment = 'retail' | 'enterprise' | 'csp' | 'lqc' | 'ai';
export type RevenueMode = 'input' | 'calculated';
export type InputMode = 'input' | 'calculated';
export type TariffSelection = 'grid' | 'ppa1' | 'ppa2' | 'blended';

export interface Period { index: number; label: string; start: Date; end: Date; year: number; monthsInPeriod: number; daysInPeriod: number; periodsPerYear: number; isOperating: boolean; operatingProration: number; }
export interface DebtInstrumentInput { id: string; kind: DebtKind; label: string; priority: number; maxShare: number; interestRate: number; tenorPeriods: number; gracePeriods: number; active?: boolean; repaymentType?: 'straight-line' | 'annuity' | 'bullet' | 'sculpted'; capitalizedInterest?: boolean; }
export interface SegmentConstantInput { active: boolean; cabinetsAvailable: number; cabinetUtilizationPct: number; rampUpReductionPct: number; powerSoldPerCabKw: number; powerDrawnRate: number; contractDuration1Years: number; contractDuration2Years: number; contractPortion1Pct: number; contractPortion2Pct: number; pricingHaircutPct: number; spacePricePerKw: number; powerPricePerKw: number; interconnectionPricePerKw: number; installationFeePerCabinet: number; salesMarketingApplies: boolean; }
export interface SegmentSeriesInput { cabinetFill: number[]; rampUpPct: number[]; effectiveRatePct: number[]; churnPct: number[]; renewalPct: number[]; }
export interface OperationsConstants { revenueMode: RevenueMode; pue: number; tariffSelection: TariffSelection; gridTariff: number; ppa1Tariff: number; ppa2Tariff: number; blendedTariff: number; hoursPerDay: number; interconnectionCostRate: number; directLabourMode: InputMode; salaryPerPersonAnnual: number; headcount: number; directLabourMarkupRate: number; propertyManagementMode: InputMode; propertyManagementFeeRate: number; facilityManagementMode: InputMode; otherOpexMarkupRate: number; facilityDirectLabourMarkupRate: number; powerFeePctOfUtility: number; salesCommissionRate: number; assetManagementFeeRate: number; salesMarketingRate: number; salesMarketingAdditionalProportion: number; insuranceAnnual: number; spvAnnual: number; downtimeMinutesPerMonth: number; downtimeReferencePricePerMinute: number; downtimeCrashProbability: number; lifecycleEnabled: boolean; lifecycleCostPctOfCapex: number; lifecycleEveryYears: number; debtorDays: number; creditorDays: number; }
export interface ConstantInputs { projectName: string; currency: string; startDate: string; periods: number; frequency: Frequency; constructionPeriods: number; epcCost: number; ownerCost: number; developmentCost: number; contingencyPct: number; vatRate: number; idcRate: number; targetGearing: number; minCashBalance: number; revenuePerPeriod: number; opexPerPeriod: number; depreciationYears: number; taxRate: number; dividendPayoutRatio: number; dividendLockupDsra: number; operations: OperationsConstants; segments: Record<CustomerSegment, SegmentConstantInput>; }
export interface SeriesInputs { revenue?: number[]; opex?: number[]; epcSpend?: number[]; vatRecovery?: number[]; directLabourCost?: number[]; propertyManagementFee?: number[]; facilityManagementFee?: number[]; costIndexation?: number[]; revenueIndexation?: number[]; electricityIndexation?: number[]; segments: Record<CustomerSegment, SegmentSeriesInput>; }
export interface SensitivityInputs { epcMultiplier: number; gearing: number; debtAllocation: Record<string, number>; rampUpReductionPct: number; opexIncreasePct: number; electricityCostIncreasePct: number; pueChange: number; utilizationChangePct: number; pricingHaircutPct: Partial<Record<CustomerSegment, number>>; }
export interface ModelInputs { constants: ConstantInputs; series: SeriesInputs; sensitivity: SensitivityInputs; debtInstruments: DebtInstrumentInput[]; }
export interface SegmentOperationRow { segment: CustomerSegment; period: number; cabinetsFilled: number; cumulativeCabinets: number; churnedCabinets: number; renewedCabinets: number; netCumulativeCabinets: number; effectiveCabinets: number; powerSoldKw: number; powerSoldMw: number; powerDrawnKw: number; powerRevenue: number; spaceRevenue: number; interconnectionRevenue: number; totalRevenue: number; installationFeeRevenue: number; maxCabinets: number; }
export interface OperationsRow { period: number; revenueInput: number; calculatedRevenue: number; revenue: number; installationFeeRevenue: number; totalPowerSoldKw: number; totalPowerSoldMw: number; totalPowerDrawnKw: number; electricityConsumptionKwh: number; electricityCost: number; interconnectionCost: number; totalUtilityExpense: number; salesCommission: number; assetManagementFee: number; directLabour: number; propertyManagementFee: number; facilityManagementFee: number; salesMarketingFee: number; insurance: number; spvCosts: number; slaPenalties: number; lifecycleCosts: number; totalOpex: number; ebitda: number; accountsReceivable: number; accountsPayable: number; changeInWorkingCapital: number; cfadsBeforeDebtService: number; segmentRevenue: Record<CustomerSegment, number>; effectiveCabinets: Record<CustomerSegment, number>; }
export interface OperationsOutput { rows: OperationsRow[]; segmentRows: SegmentOperationRow[]; validationErrors: string[]; validationChecks: Record<string, boolean>; }
export interface DebtScheduleRow { period: number; instrumentId: string; opening: number; draw: number; interest: number; principal: number; closing: number; facilitySize: number; allocationPct: number; }
export interface ModelRow { period: number; revenue: number; opex: number; ebitda: number; vatIn: number; vatOut: number; vatNet: number; depreciation: number; ebit: number; interest: number; tax: number; dividends: number; cash: number; accountsReceivable: number; accountsPayable: number; ppeOpening: number; capex: number; ppeClosing: number; debtOpening: number; debtDraw: number; debtPrincipal: number; debtClosing: number; equity: number; assets: number; liabilitiesEquity: number; }
export interface ModelOutputs { timeline: Period[]; operations: OperationsOutput; capex: number[]; idc: number[]; totalUses: number; debtSize: number; equitySize: number; debtSchedules: DebtScheduleRow[]; rows: ModelRow[]; metrics: Record<string, number>; checks: Record<string, boolean>; validationErrors: string[]; solver: { converged: boolean; iterations: number; maxDifference: number; errorMessage?: string }; }
