import React,{useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{defaultInputs,runModel}from'./model/financeEngine';import type{CustomerSegment,ModelInputs}from'./model/types';import'./style.css';
const tabs=['Constant Inputs','Series Inputs','Sensitivity Inputs','Summary','CAPEX','Drawdown','Operations','VAT','Repayment','Accounting','Tax','Dividend','Analysis']as const;const segs:CustomerSegment[]=['retail','enterprise','csp','lqc','ai'];const labels={en:{run:'Run Model',out:'Out of date',ok:'Model current',auto:'Auto-run',calc:'Calculated',input:'Input'},tr:{run:'Modeli Çalıştır',out:'Güncel değil',ok:'Model güncel',auto:'Otomatik çalıştır',calc:'Hesaplanan',input:'Girdi'}};
function clone<T>(x:T):T{return JSON.parse(JSON.stringify(x))}function download(n:string,t:string,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([t],{type}));a.download=n;a.click()}function csv(rows:Record<string,unknown>[]){const k=Object.keys(rows[0]??{});return[k.join(','),...rows.map(r=>k.map(x=>JSON.stringify(r[x]??'')).join(','))].join('\n')}
function App(){const stored=localStorage.getItem('dcfm-scenarios');const [scenarios,setScenarios]=useState<Record<string,ModelInputs>>(()=>stored?JSON.parse(stored):{Base:defaultInputs,Upside:defaultInputs,Downside:defaultInputs,Custom:defaultInputs});const[caseName,setCaseName]=useState('Base');const[inputs,setInputs]=useState<ModelInputs>(()=>clone(scenarios.Base));const[tab,setTab]=useState<(typeof tabs)[number]>('Constant Inputs');const[theme,setTheme]=useState('light');const[lang,setLang]=useState<'en'|'tr'>('en');const[dirty,setDirty]=useState(false);const[changed,setChanged]=useState('');const[auto,setAuto]=useState(false);const[status,setStatus]=useState('Success');const[prev,setPrev]=useState(()=>runModel(defaultInputs));const[out,setOut]=useState(()=>runModel(inputs));const t=labels[lang];function persist(next:ModelInputs,name=caseName){const ns={...scenarios,[name]:next};setScenarios(ns);localStorage.setItem('dcfm-scenarios',JSON.stringify(ns));localStorage.setItem('dcfm-inputs',JSON.stringify(next));}
function update(next:ModelInputs,label:string){setInputs(next);persist(next);setDirty(true);setChanged(label);if(auto)setTimeout(()=>run(),0)}function run(){setStatus('Calculating operations…');setTimeout(()=>{setStatus('Solving IDC circularity…');setTimeout(()=>{try{const next=runModel(inputs);setPrev(out);setOut(next);setDirty(false);setStatus(next.validationErrors.length?'Completed with validation warnings':'Success')}catch(e){setStatus(`Error: ${(e as Error).message}`)}},80)},80)}const delta=(k:string)=>{const a=out.metrics[k]??0,b=prev.metrics[k]??0,d=a-b;return `${fmt(a)} (${d>=0?'+':''}${fmt(d)})`};
const num=(label:string,value:number,on:(n:number)=>void,unit='',help='')=><label className="field"><span>{label}<small>{unit} {help}</small></span><input type="number" value={value} onChange={e=>on(Number(e.target.value))}/></label>;
function ScenarioBar(){return <div className="scenario"><select value={caseName}onChange={e=>{const n=e.target.value;setCaseName(n);setInputs(clone(scenarios[n]));setDirty(true);setChanged(`Scenario: ${n}`)}}>{Object.keys(scenarios).map(s=><option>{s}</option>)}</select><button onClick={()=>{const n=`Custom ${Object.keys(scenarios).length}`;persist(clone(inputs),n);setCaseName(n)}}>Duplicate case</button><button onClick={()=>update(clone(defaultInputs),'Reset case')}>Reset default</button><label><input type="checkbox"checked={auto}onChange={e=>setAuto(e.target.checked)}/>{t.auto}</label></div>}
function Impact(){const keys=['totalRevenue','ebitda','ebitdaMargin','totalOpex','totalCapex','totalIDC','totalDebt','equityIRR','projectIRR','minimumDSCR','LLCR'];return <aside className="impact"><b>What-if / Impact</b>{keys.map(k=><div><span>{k}</span><strong>{delta(k)}</strong></div>)}</aside>}
const setConst=(patch:Partial<ModelInputs['constants']>,label:string)=>update({...inputs,constants:{...inputs.constants,...patch}},label);
const setOps=(patch:Partial<ModelInputs['constants']['operations']>,label:string)=>setConst({operations:{...inputs.constants.operations,...patch}},label);
const setSeg=(s:CustomerSegment,patch:Partial<ModelInputs['constants']['segments'][CustomerSegment]>,label:string)=>setConst({segments:{...inputs.constants.segments,[s]:{...inputs.constants.segments[s],...patch}}},label);
const render=()=>{
 if(tab==='Constant Inputs')return <><ScenarioBar/><Impact/><div className="cards">
  <section className="card wide"><h3>Project & financing</h3>
   {num('EPC cost',inputs.constants.epcCost,n=>setConst({epcCost:n},'EPC cost'),'USD','Constant')}
   {num('Target gearing',inputs.constants.targetGearing,n=>update({...inputs,constants:{...inputs.constants,targetGearing:n},sensitivity:{...inputs.sensitivity,gearing:n}},'Target gearing'),'%','Constant')}
   {num('PUE',inputs.constants.operations.pue,n=>setOps({pue:n},'PUE'),'x','Constant')}
   {num('Debtor days',inputs.constants.operations.debtorDays,n=>setOps({debtorDays:n},'Debtor days'),'days','Constant')}
   <label>Total revenue mode<select value={inputs.constants.operations.revenueMode} onChange={e=>setOps({revenueMode:e.target.value as 'input'|'calculated'},'Revenue mode')}><option value="calculated">Calculated from segments</option><option value="input">Direct input series</option></select></label>
   <label>Direct labour mode<select value={inputs.constants.operations.directLabourMode} onChange={e=>setOps({directLabourMode:e.target.value as 'input'|'calculated'},'Direct labour mode')}><option value="calculated">Calculated</option><option value="input">Input</option></select></label>
   <label>Property management mode<select value={inputs.constants.operations.propertyManagementMode} onChange={e=>setOps({propertyManagementMode:e.target.value as 'input'|'calculated'},'PM mode')}><option value="calculated">Calculated</option><option value="input">Input</option></select></label>
  </section>
  {segs.map(s=>{const x=inputs.constants.segments[s];return <section className="card wide" key={s}><h3>{s.toUpperCase()}</h3>
   <details open><summary>Capacity & utilization</summary><label><input type="checkbox" checked={x.active} onChange={e=>setSeg(s,{active:e.target.checked},`${s} active`)}/> Active</label>{num('Cabinets available',x.cabinetsAvailable,n=>setSeg(s,{cabinetsAvailable:n},`${s} cabinets`),'cabs')}{num('Utilization',x.cabinetUtilizationPct,n=>setSeg(s,{cabinetUtilizationPct:n},`${s} utilization`),'0-1')}</details>
   <details><summary>Fill-up and ramp-up</summary>{num('Ramp-up reduction',x.rampUpReductionPct,n=>setSeg(s,{rampUpReductionPct:n},`${s} ramp reduction`),'0-1')}<p>Periodic fill, ramp-up and effective-rate schedules are editable on Series Inputs.</p></details>
   <details><summary>Churn / renewal</summary>{num('Contract duration 1',x.contractDuration1Years,n=>setSeg(s,{contractDuration1Years:n},`${s} duration 1`),'years')}{num('Contract duration 2',x.contractDuration2Years,n=>setSeg(s,{contractDuration2Years:n},`${s} duration 2`),'years')}{num('Contract portion 1',x.contractPortion1Pct,n=>setSeg(s,{contractPortion1Pct:n},`${s} contract 1`),'0-1')}{num('Contract portion 2',x.contractPortion2Pct,n=>setSeg(s,{contractPortion2Pct:n},`${s} contract 2`),'0-1')}</details>
   <details><summary>Pricing</summary>{num('Space price / kW-mo',x.spacePricePerKw,n=>setSeg(s,{spacePricePerKw:n},`${s} space price`))}{num('Power price / kW-mo',x.powerPricePerKw,n=>setSeg(s,{powerPricePerKw:n},`${s} power price`))}{num('Interconnection price / kW-mo',x.interconnectionPricePerKw,n=>setSeg(s,{interconnectionPricePerKw:n},`${s} interconnection price`))}{num('Pricing haircut',x.pricingHaircutPct,n=>setSeg(s,{pricingHaircutPct:n},`${s} haircut`),'0-1')}</details>
   <details><summary>Power assumptions</summary>{num('kW/cab',x.powerSoldPerCabKw,n=>setSeg(s,{powerSoldPerCabKw:n},`${s} kW/cab`))}{num('Power drawn rate',x.powerDrawnRate,n=>setSeg(s,{powerDrawnRate:n},`${s} draw rate`),'0-1')}</details>
  </section>})}</div></>;
 if(tab==='Series Inputs')return <><Impact/><p>Advanced editable JSON series. Segment cards on Constant Inputs cover common operational drivers.</p><textarea value={JSON.stringify(inputs.series,null,2)} onChange={e=>update({...inputs,series:JSON.parse(e.target.value||'{}')},'Series inputs')}/></>;
 if(tab==='Sensitivity Inputs')return <><Impact/><div className="grid">{num('Ramp-up reduction',inputs.sensitivity.rampUpReductionPct,n=>update({...inputs,sensitivity:{...inputs.sensitivity,rampUpReductionPct:n}},'Ramp-up reduction'))}{num('OPEX increase',inputs.sensitivity.opexIncreasePct,n=>update({...inputs,sensitivity:{...inputs.sensitivity,opexIncreasePct:n}},'OPEX increase'))}{num('Electricity cost increase',inputs.sensitivity.electricityCostIncreasePct,n=>update({...inputs,sensitivity:{...inputs.sensitivity,electricityCostIncreasePct:n}},'Electricity sensitivity'))}{num('PUE change',inputs.sensitivity.pueChange,n=>update({...inputs,sensitivity:{...inputs.sensitivity,pueChange:n}},'PUE change'))}</div></>;
 if(tab==='Summary')return <><Cards data={{...pick(out.metrics,['totalCabinetsAvailable','effectiveCabinets','totalPowerSoldMw','totalPowerDrawnMw','totalRevenue','ebitda','ebitdaMargin','totalCapex','totalIDC','totalDebt','totalEquity','minimumDSCR','LLCR','equityIRR','projectIRR'])}}/><h3>Audit status</h3><Cards data={out.checks}/><Chart rows={out.operations.rows.map(r=>({label:String(r.period),Revenue:r.revenue,EBITDA:r.ebitda,PowerMW:r.totalPowerSoldMw}))}/></>;
 if(tab==='Operations')return <><h3>Revenue section</h3><Table rows={out.operations.rows.map(r=>({period:r.period,revenue:r.revenue,installation:r.installationFeeRevenue,powerSoldMw:r.totalPowerSoldMw,powerDrawnKw:r.totalPowerDrawnKw,...r.segmentRevenue}))}/><h3>OPEX section</h3><Table rows={out.operations.rows.map(r=>({period:r.period,electricityCost:r.electricityCost,interconnectionCost:r.interconnectionCost,utility:r.totalUtilityExpense,salesCommission:r.salesCommission,assetManagement:r.assetManagementFee,directLabour:r.directLabour,propertyManagement:r.propertyManagementFee,facilityManagement:r.facilityManagementFee,salesMarketing:r.salesMarketingFee,insurance:r.insurance,spv:r.spvCosts,sla:r.slaPenalties,lifecycle:r.lifecycleCosts,totalOpex:r.totalOpex}))}/><h3>Cash flow</h3><Table rows={out.operations.rows.map(r=>({period:r.period,revenue:r.revenue,opex:r.totalOpex,ebitda:r.ebitda,changeWC:r.changeInWorkingCapital,cfads:r.cfadsBeforeDebtService}))}/><Chart rows={out.operations.rows.map(r=>({label:String(r.period),Revenue:r.revenue,EBITDA:r.ebitda,OPEX:r.totalOpex,PowerMW:r.totalPowerSoldMw}))}/></>;
 if(tab==='CAPEX')return <Table rows={out.rows.map(r=>({period:r.period,capex:r.capex,ppeClosing:r.ppeClosing}))}/>;
 if(tab==='Drawdown')return <><Cards data={{totalUses:out.totalUses,totalDebt:out.debtSize,totalEquity:out.equitySize,usesSourcesCheck:out.totalUses-out.debtSize-out.equitySize}}/><Table rows={out.debtSchedules.filter(r=>r.draw>0)}/></>;
 if(tab==='VAT')return <Table rows={out.rows.map(r=>({period:r.period,vatIn:r.vatIn,vatOut:r.vatOut,vatNet:r.vatNet}))}/>;
 if(tab==='Repayment')return <Table rows={out.debtSchedules}/>;
 if(tab==='Accounting')return <Table rows={out.rows.map(r=>({period:r.period,depreciation:r.depreciation,ebit:r.ebit,cash:r.cash,ar:r.accountsReceivable,ap:r.accountsPayable,assets:r.assets,liabilitiesEquity:r.liabilitiesEquity}))}/>;
 if(tab==='Tax')return <Table rows={out.rows.map(r=>({period:r.period,ebit:r.ebit,interest:r.interest,tax:r.tax}))}/>;
 if(tab==='Dividend')return <Table rows={out.rows.map(r=>({period:r.period,dividends:r.dividends,cash:r.cash}))}/>;
 return <><Cards data={out.metrics}/><h3>Case comparison</h3><Table rows={Object.entries(scenarios).map(([name,i])=>{const o=runModel(i);return{case:name,totalRevenue:o.metrics.totalRevenue,EBITDA:o.metrics.ebitda,EquityIRR:o.metrics.equityIRR,MinDSCR:o.metrics.minimumDSCR,UsesSources:o.checks.usesSourcesBalanced,BS:o.checks.balanceSheetBalanced}})}/><pre>{out.validationErrors.join('\n')||'No validation errors'}</pre></>};
return <main className={theme}><nav><strong>DC-FM</strong><span className={dirty?'dirty':'ok'}>{dirty?t.out:t.ok}{changed&&` — ${changed}`}</span><button onClick={run}>{status.includes('Calculating')||status.includes('Solving')?<span className="spin"/>:null}{t.run}</button><button onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme}</button><select value={lang}onChange={e=>setLang(e.target.value as 'en'|'tr')}><option value="en">English</option><option value="tr">Türkçe</option></select><button onClick={()=>download('inputs.json',JSON.stringify(inputs,null,2))}>Export JSON</button><label className="button">Import JSON<input hidden type="file"onChange={async e=>{const f=e.target.files?.[0];if(f)update(JSON.parse(await f.text()),'Imported JSON')}}/></label><button onClick={()=>download('outputs.csv',csv(out.rows as unknown as Record<string,unknown>[]),'text/csv')}>Export CSV</button></nav><div className="status">{status}</div><section className="tabs">{tabs.map(x=><button className={x===tab?'active':''}onClick={()=>setTab(x)}>{x}</button>)}</section><section className="panel">{render()}</section></main>}
function fmt(v:number){return v.toLocaleString(undefined,{maximumFractionDigits:2})}function pick(o:Record<string,number>,keys:string[]){return Object.fromEntries(keys.map(k=>[k,o[k]]))}function Cards({data}:{data:Record<string,unknown>}){return <div className="cards">{Object.entries(data).map(([k,v])=><div className="card"><b>{k}</b><span>{typeof v==='number'?fmt(v):String(v)}</span></div>)}</div>}function Table({rows}:{rows:object[]}){const keys=Object.keys(rows[0]??{});return <div className="tablewrap"><table><thead><tr>{keys.map(k=><th>{k}</th>)}</tr></thead><tbody>{rows.map((row,i)=>{const r=row as Record<string,unknown>;return <tr key={i}>{keys.map(k=><td>{typeof r[k]==='number'?fmt(r[k] as number):String(r[k])}</td>)}</tr>})}</tbody></table></div>}function Chart({rows}:{rows:Record<string,number|string>[]}){const keys=Object.keys(rows[0]??{}).filter(k=>k!=='label');const max=Math.max(1,...rows.flatMap(r=>keys.map(k=>Number(r[k])||0)));return <div className="chart">{rows.slice(-16).map((r,i)=><div className="bar"key={i}>{keys.map(k=><span title={`${k}: ${fmt(Number(r[k]))}`}style={{height:`${Math.max(2,(Number(r[k])||0)/max*100)}%`}}/>)}<small>{r.label}</small></div>)}</div>}
createRoot(document.getElementById('root')!).render(<App/>);
