import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { defaultInputs, runModel } from './model/financeEngine';
import type { ModelInputs } from './model/types';
import './style.css';
const tabs=['Constant Inputs','Series Inputs','Sensitivity Inputs','Summary','CAPEX','Drawdown','Operations','VAT','Repayment','Accounting','Tax','Dividend','Analysis'] as const;
const labels={en:{run:'Run Model',export:'Export JSON',import:'Import JSON',csv:'Export CSV'},tr:{run:'Modeli Çalıştır',export:'JSON Dışa Aktar',import:'JSON İçe Aktar',csv:'CSV Dışa Aktar'}};
function download(name:string,text:string,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();}
function toCsv(rows: Record<string, unknown>[]) { const keys=Object.keys(rows[0]??{}); return [keys.join(','),...rows.map(r=>keys.map(k=>JSON.stringify(r[k]??'')).join(','))].join('\n'); }
function App(){ const [inputs,setInputs]=useState<ModelInputs>(()=>JSON.parse(localStorage.getItem('dcfm-inputs')||'null')||defaultInputs); const [tab,setTab]=useState<(typeof tabs)[number]>('Constant Inputs'); const [theme,setTheme]=useState('light'); const [lang,setLang]=useState<'en'|'tr'>('en'); const [runId,setRunId]=useState(0); const out=useMemo(()=>runModel(inputs),[inputs,runId]); const t=labels[lang]; function save(next:ModelInputs){setInputs(next);localStorage.setItem('dcfm-inputs',JSON.stringify(next));}
 const inputNumber=(label:string,value:number,onChange:(n:number)=>void)=><label>{label}<input type="number" value={value} onChange={e=>onChange(Number(e.target.value))}/></label>;
 const render=()=>{ if(tab==='Constant Inputs')return <div className="grid">{inputNumber('EPC Cost',inputs.constants.epcCost,n=>save({...inputs,constants:{...inputs.constants,epcCost:n}}))}{inputNumber('Target Gearing',inputs.constants.targetGearing,n=>save({...inputs,constants:{...inputs.constants,targetGearing:n},sensitivity:{...inputs.sensitivity,gearing:n}}))}{inputNumber('VAT Rate',inputs.constants.vatRate,n=>save({...inputs,constants:{...inputs.constants,vatRate:n}}))}{inputNumber('Revenue / Period',inputs.constants.revenuePerPeriod,n=>save({...inputs,constants:{...inputs.constants,revenuePerPeriod:n}}))}{inputNumber('Opex / Period',inputs.constants.opexPerPeriod,n=>save({...inputs,constants:{...inputs.constants,opexPerPeriod:n}}))}</div>;
 if(tab==='Series Inputs')return <textarea value={JSON.stringify(inputs.series,null,2)} onChange={e=>save({...inputs,series:JSON.parse(e.target.value||'{}')})}/>;
 if(tab==='Sensitivity Inputs')return <div className="grid">{inputNumber('EPC Multiplier',inputs.sensitivity.epcMultiplier,n=>save({...inputs,sensitivity:{...inputs.sensitivity,epcMultiplier:n}}))}{inputNumber('Gearing',inputs.sensitivity.gearing,n=>save({...inputs,sensitivity:{...inputs.sensitivity,gearing:n}}))}<textarea value={JSON.stringify(inputs.sensitivity.debtAllocation,null,2)} onChange={e=>save({...inputs,sensitivity:{...inputs.sensitivity,debtAllocation:JSON.parse(e.target.value||'{}')}})}/></div>;
 const rows=out.rows; if(tab==='Summary')return <Cards data={{Uses:out.totalUses,Debt:out.debtSize,Equity:out.equitySize,...out.metrics}}/>; if(tab==='CAPEX')return <Table rows={rows.map(r=>({period:r.period,capex:r.capex,ppeClosing:r.ppeClosing}))}/>; if(tab==='Drawdown')return <Table rows={out.debtSchedules.filter(r=>r.draw>0)}/>; if(tab==='Operations')return <Table rows={rows.map(r=>({period:r.period,revenue:r.revenue,opex:r.opex,ebitda:r.ebitda}))}/>; if(tab==='VAT')return <Table rows={rows.map(r=>({period:r.period,vatIn:r.vatIn,vatOut:r.vatOut,vatNet:r.vatNet}))}/>; if(tab==='Repayment')return <Table rows={out.debtSchedules}/>; if(tab==='Accounting')return <Table rows={rows.map(r=>({period:r.period,depreciation:r.depreciation,ebit:r.ebit,assets:r.assets,liabilitiesEquity:r.liabilitiesEquity}))}/>; if(tab==='Tax')return <Table rows={rows.map(r=>({period:r.period,ebit:r.ebit,interest:r.interest,tax:r.tax}))}/>; if(tab==='Dividend')return <Table rows={rows.map(r=>({period:r.period,dividends:r.dividends,cash:r.cash}))}/>; return <><Cards data={out.checks}/><pre>{out.validationErrors.join('\n')||'No validation errors'}</pre></>; };
 return <main className={theme}><nav><strong>DC-FM</strong><button onClick={()=>setRunId(x=>x+1)}>{t.run}</button><button onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme}</button><select value={lang} onChange={e=>setLang(e.target.value as 'en'|'tr')}><option value="en">English</option><option value="tr">Türkçe</option></select><button onClick={()=>download('inputs.json',JSON.stringify(inputs,null,2))}>{t.export}</button><label className="button">{t.import}<input hidden type="file" onChange={async e=>{const f=e.target.files?.[0]; if(f) save(JSON.parse(await f.text()));}}/></label><button onClick={()=>download('outputs.csv',toCsv(out.rows as unknown as Record<string,unknown>[]),'text/csv')}>{t.csv}</button></nav><section className="tabs">{tabs.map(x=><button className={x===tab?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</section><section className="panel">{render()}</section></main>; }
function Cards({data}:{data:Record<string,unknown>}){return <div className="cards">{Object.entries(data).map(([k,v])=><div className="card"><b>{k}</b><span>{typeof v==='number'?v.toLocaleString(undefined,{maximumFractionDigits:2}):String(v)}</span></div>)}</div>}
function Table({rows}:{rows:Record<string,unknown>[]}){const keys=Object.keys(rows[0]??{});return <table><thead><tr>{keys.map(k=><th>{k}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{keys.map(k=><td>{typeof r[k]==='number'?(r[k] as number).toFixed(2):String(r[k])}</td>)}</tr>)}</tbody></table>}
createRoot(document.getElementById('root')!).render(<App/>);
